##### 1.Sayılardan oluşan bir boyutlu array oluşturun. Arrayi oluştururken sayıların veri tipini integer olarak belirtelim.

Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakalım.

In [4]:

import numpy as np
bir_boyut = np.array([3,5,15,23],dtype="int")
print(bir_boyut)

##boyut
print(bir_boyut.ndim)
##eleman-sayisi
print(bir_boyut.size)

[ 3  5 15 23]
1
4


##### 2. Aşağıda verilen iki boyutlu ve üç boyutlu arrayi oluşturalım. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşalım. 

İki boyutlu array:
[[1,2,6,7],
 [4,3,9,5]]

Üç boyutlu array:
[[[7,5,14],[21,8,11]],
 [[8,6,20],[14,3,9]]]

 

In [15]:
import numpy as np
new_array = np.array([[1,2,6,7],[4,3,9,5]])
new_array
print("{} boyutlu dizinin eleman sayısı: {}".format(new_array,new_array.size))
print("{} boyutlu dizinin boyut sayısı: {}".format(new_array,new_array.ndim))
print("{} boyutlu dizinin satır-sütün bilgisi: {}".format(new_array,np.shape(new_array)))
print("--------------------")
uc_boyutlu = np.array([[[7,5,14],[21,8,11]],
 [[8,6,20],[14,3,9]]])
uc_boyutlu
print("{} boyutlu dizinin eleman sayısı : {}".format(uc_boyutlu,uc_boyutlu.size))
print("{} boyutlu dizinin boyut sayısı : {}".format(uc_boyutlu,uc_boyutlu.ndim))
print("{} boyutlu dizinin satır-sütün bilgisi: {}".format(uc_boyutlu,np.shape(uc_boyutlu)))

[[1 2 6 7]
 [4 3 9 5]] boyutlu dizinin eleman sayısı: 8
[[1 2 6 7]
 [4 3 9 5]] boyutlu dizinin boyut sayısı: 2
[[1 2 6 7]
 [4 3 9 5]] boyutlu dizinin satır-sütün bilgisi: (2, 4)
--------------------
[[[ 7  5 14]
  [21  8 11]]

 [[ 8  6 20]
  [14  3  9]]] boyutlu dizinin eleman sayısı : 12
[[[ 7  5 14]
  [21  8 11]]

 [[ 8  6 20]
  [14  3  9]]] boyutlu dizinin boyut sayısı : 3
[[[ 7  5 14]
  [21  8 11]]

 [[ 8  6 20]
  [14  3  9]]] boyutlu dizinin satır-sütün bilgisi: (2, 2, 3)


##### 3. İstenilen elamanlara ulaşmak için arrayler üzerinde indexleme işlemi yapalım

In [16]:
#İki boyutlu arraydaki 2 elemanına ulaşalım
import numpy as np
new_array = np.array([[1,2,6,7],[4,3,9,5]])
new_array[0,1]

2

In [17]:
#İki boyutlu arraydaki 7 elemanına ulaşalım
new_array[0,3]

7

In [18]:
#Üç boyutlu arraydaki 9 elemanına ulaşalım
uc_boyutlu = np.array([[[7,5,14],[21,8,11]],
 [[8,6,20],[14,3,9]]])
uc_boyutlu[1][1][2]

9

In [19]:
#Üç boyutlu arraydaki 5 elemanına ulaşalım
uc_boyutlu[0][0][1]

5

##### 4. Arrayler üzerinde slicing işlemi uygulayalım.

In [20]:
#İki boyutlu arraydaki 2,6 elemanlarına ulaşalım
new_array = np.array([[1,2,6,7],[4,3,9,5]])
new_array[0,1:3]

array([2, 6])

In [21]:
#İki boyutlu arraydaki 3,9,5 elemanlarına ulaşalım
new_array[1,1:4]


array([3, 9, 5])

In [22]:
#Üç boyutlu arraydaki 21,8,11 elemanlarına ulaşalım
uc_boyutlu = np.array([[[7,5,14],[21,8,11]],
 [[8,6,20],[14,3,9]]])
uc_boyutlu[0,1]


array([21,  8, 11])

In [23]:
#Üç boyutlu arraydaki 6,20 elemanlarına ulaşalım
uc_boyutlu[1][0][1:3]


array([ 6, 20])

##### 5. 5 satır 3 sütunluk sıfırlardan ve birlerden oluşan iki tane iki boyutlu array oluşturalım. Bu arrayleri satır ve sütun bazında birleştirelim.

In [28]:
a=np.zeros((5,3),dtype="int")
a

b=np.ones((5,3),dtype="int")
b

np.concatenate([a,b])
np.concatenate([a,b],axis=1)

array([[0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1]])